/**
 * Type definitions for chart analysis insights generated by ChatGPT
 */

export interface ChartInsight {
    title: string
    description: string
    insights: string[]
    subject: 'math' | 'reading' | null
    grade: string | null
    keyMetrics: string[]
    chart_path: string
    chart_name: string
    error?: string
}

export interface ChartAnalysisResponse {
    success: boolean
    analyses: ChartInsight[]
    count: number
    error?: string
}

/**
 * Map chart path to its insights
 */
export type ChartInsightsMap = Map<string, ChartInsight>
